In [2]:
import pandas as pd
import numpy as np
import seaborn as sn
import matplotlib.pyplot as plt

In [3]:
data = pd.read_csv("data_out.csv")
data.dropna(inplace=True)

In [23]:
for x in data[["fname","liveness_score","embed","embed_notnull"]].values[:10]:
    print(x[0])
    print(x[1])
    print(x[2])
    l = npx[2]
    # hm = sn.heatmap(data = x[2])
    plt.show()
    

1.mp4
0
[[1.         0.9994656  0.99975627 ... 0.         0.         0.        ]
 [0.9994656  1.         0.99955912 ... 0.         0.         0.        ]
 [0.99975627 0.99955912 1.         ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]]
2.mp4
1
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
3.mp4
1
[[0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 1.         0.98519411 0.98790798]
 [0.         0.         0.         ... 0.98519411 1.         0.99237347]
 [0.  

array(['[[1.         0.9994656  0.99975627 ... 0.         0.         0.        ]\n [0.9994656  1.         0.99955912 ... 0.         0.         0.        ]\n [0.99975627 0.99955912 1.         ... 0.         0.         0.        ]\n ...\n [0.         0.         0.         ... 0.         0.         0.        ]\n [0.         0.         0.         ... 0.         0.         0.        ]\n [0.         0.         0.         ... 0.         0.         0.        ]]',
       '[[0. 0. 0. ... 0. 0. 0.]\n [0. 0. 0. ... 0. 0. 0.]\n [0. 0. 0. ... 0. 0. 0.]\n ...\n [0. 0. 0. ... 0. 0. 0.]\n [0. 0. 0. ... 0. 0. 0.]\n [0. 0. 0. ... 0. 0. 0.]]',
       '[[0.         0.         0.         ... 0.         0.         0.        ]\n [0.         0.         0.         ... 0.         0.         0.        ]\n [0.         0.         0.         ... 0.         0.         0.        ]\n ...\n [0.         0.         0.         ... 1.         0.98519411 0.98790798]\n [0.         0.         0.         ... 0.98519411 1.      

In [3]:
bounding_boxes = []
bounding_boxes = np.vstack(bounding_boxes)

ValueError: need at least one array to concatenate